force-app/main/default/objects/MovieWishList__c/MovieWishList__c.object-meta.xml
<CustomObject>
    <label>Movie Wish List</label>
    <nameField>
        <label>Movie  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Movies Wish List</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/MovieWishList__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Movie Wish Lists</relationshipLabel>
    <relationshipName>Movie_Wish_Lists</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/MovieWishList__c/fields/MovieName__c.field-meta.xml
<CustomField>
    <fullName>MovieName__c</fullName>
    <description>The name of the movie that you want to be available in the movie store.</description>
    <label>Movie Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/MovieWishListController.cls
public with sharing class MovieWishListController {

    @AuraEnabled
    public static String createWishMovie(String name, String ContactId) {
        MovieWishList__c movieWish = new MovieWishList__c();
        movieWish.MovieName__c = name;
        movieWish.Contact__c = ContactId;
        try {
            
            insert movieWish;
            return 'success';
        } catch (Exception e) {
            return 'error';
            
        }

    }
}