force-app/main/default/objects/Contact/fields/ContactStatus__c.field-meta.xml
<CustomField>
    <fullName>ContactStatus__c</fullName>
    <defaultValue>&apos;Normal&apos;</defaultValue>
    <label>Contact Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Normal</fullName>
                <default>true</default>
                <label>Normal</label>
            </value>
            <value>
                <fullName>Defaulting</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Inventory__c/Inventory__c.object-meta.xml
<CustomObject>
    <label>Inventory</label>
    <nameField>
        <label>Inventory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Inventories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Inventory__c/recordTypes/Movie.recordType-meta.xml
<RecordType>
    <fullName>Movie</fullName>
    <active>true</active>
    <label>Movie</label>
</RecordType>

force-app/main/default/objects/Inventory_Item__c/Inventory_Item__c.object-meta.xml
<CustomObject>
    <label>Inventory Item</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Inventory Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inventory Itens</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Inventory_Item__c/fields/Inventory__c.field-meta.xml
<CustomField>
    <fullName>Inventory__c</fullName>
    <label>Inventory</label>
    <referenceTo>Inventory__c</referenceTo>
    <relationshipLabel>Inventory Itens</relationshipLabel>
    <relationshipName>InventoryItens</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Inventory_Item__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Available</fullName>
            </value>
            <value>
                <fullName>Rented</fullName>
            </value>
            <value>
                <fullName>Reserved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Rent__c/Rent__c.object-meta.xml
<CustomObject>
    <label>Rent</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Rent Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rents</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Rent__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Rents</relationshipLabel>
    <relationshipName>Rents</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Rent__c/fields/Inventory_Item__c.field-meta.xml
<CustomField>
    <fullName>Inventory_Item__c</fullName>
    <label>Inventory Item</label>
    <referenceTo>Inventory_Item__c</referenceTo>
    <relationshipLabel>Rents</relationshipLabel>
    <relationshipName>Rents</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Rent__c/fields/LocationDate__c.field-meta.xml
<CustomField>
    <fullName>LocationDate__c</fullName>
    <label>Location Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Rent__c/fields/LocationFinished__c.field-meta.xml
<CustomField>
    <fullName>LocationFinished__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Location Finished</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ReservedItem__c/ReservedItem__c.object-meta.xml
<CustomObject>
    <label>Reserved Item</label>
    <nameField>
        <displayFormat>RE-{0000}</displayFormat>
        <label>Reserved Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reserved Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ReservedItem__c/fields/ContactName__c.field-meta.xml
<CustomField>
    <fullName>ContactName__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact Name</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Reserved Items</relationshipLabel>
    <relationshipName>Reserved_Items</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ReservedItem__c/fields/Reservation__c.field-meta.xml
<CustomField>
    <fullName>Reservation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Reservation</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>This item is available!</errorMessage>
        <filterItems>
            <field>Inventory__c.InventoryStatus__c</field>
            <operation>equals</operation>
            <value>Unavailable</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Inventory__c</referenceTo>
    <relationshipLabel>Reserved Items</relationshipLabel>
    <relationshipName>reservation</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ReservedItem__c/fields/ReservationStatus__c.field-meta.xml
<CustomField>
    <fullName>ReservationStatus__c</fullName>
    <label>Reservation Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Canceled</fullName>
                <color>#FF0000</color>
                <label>Canceled</label>
            </value>
            <value>
                <fullName>Reserved</fullName>
            </value>
            <value>
                <fullName>Waiting</fullName>
                <default>true</default>
                <label>Waiting</label>
            </value>
            <value>
                <fullName>Successful Rented</fullName>
                <color>#33FF33</color>
                <label>Successful Rented</label>
            </value>
            <value>
                <fullName>Time Counting Down</fullName>
                <color>#FFFF66</color>
                <label>Time Counting Down</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/RentBOTest.cls
@isTest
public class RentBOTest {
 
@isTest static void cantCreatRentWithoutContact(){
    Inventory__c inventory = new Inventory__c(RecordTypeId = '0128b000001MpG2AAK', Name = 'Test Movie');
    Inventory_Item__c inventoryItem = new Inventory_Item__c(Inventory__c = inventory.Id, Status__c = 'Available');

    Rent__c rent = new Rent__c();
        rent.Inventory_Item__c = inventoryItem.Id;
        System.debug('inventoryItem.Id : '+inventoryItem.Id);

        rent.LocationDate__c = Date.today();
        rent.CloseDate__c = Date.today().addMonths(1);

    Test.startTest();
    Database.SaveResult result = Database.insert(rent, false);
    Test.stopTest();

    System.assert(result.getErrors().size() > 0);
    System.assert(result.isSuccess() == false, 'You should insert Contact__c');
}
@isTest static void cantCreatRent(){
    Rent__c rent = new Rent__c();
    Test.startTest();
    Database.SaveResult result = Database.insert(rent, false);
    Test.stopTest();

    System.assert(result.getErrors().size() > 0);
    System.assert(result.isSuccess() == false, 'You should insert Inventory_Item__c and Contact__c');
}
@isTest static void createOneRentSuccess() {
    Inventory__c inventory = new Inventory__c(RecordTypeId = '0128b000001MpG2AAK', Name = 'Test Movie');
    insert inventory;
    Inventory_Item__c inventoryItem = new Inventory_Item__c(Inventory__c = inventory.Id, Status__c = 'Available');
    insert inventoryItem;
    Contact contactTest = new Contact(LastName = 'Test Movie');
    insert contactTest;


    Rent__c rent = new Rent__c();
        rent.Contact__c = contactTest.Id;
        System.debug('contactTest.Id : '+contactTest.Id);

        rent.Inventory_Item__c = inventoryItem.Id;
        System.debug('inventoryItem.Id : '+inventoryItem.Id);

        rent.LocationDate__c = Date.today();
        rent.CloseDate__c = Date.today().addMonths(1);

    Test.startTest();
    Database.SaveResult result = Database.insert(rent, false);
    Test.stopTest();

    Inventory_Item__c chckingStatus = [SELECT Status__c FROM Inventory_Item__c WHERE id = :inventoryItem.Id LIMIT 1];
    System.AssertEquals('Rented', chckingStatus.Status__c);

    System.Assert(result.isSuccess());

}
@isTest static void alreadyRented() {
    Inventory__c inventory = new Inventory__c(RecordTypeId = '0128b000001MpG2AAK', Name = 'Test Movie');
    insert inventory;
    Inventory_Item__c inventoryItem = new Inventory_Item__c(Inventory__c = inventory.Id, Status__c = 'Available');
    insert inventoryItem;
    Contact contactTest = new Contact(LastName = 'Test Movie');
    insert contactTest;


    Rent__c rent = new Rent__c();
        rent.Contact__c = contactTest.Id;
        System.debug('contactTest.Id : '+contactTest.Id);

        rent.Inventory_Item__c = inventoryItem.Id;
        System.debug('inventoryItem.Id : '+inventoryItem.Id);

        rent.LocationDate__c = Date.today();
        rent.CloseDate__c = Date.today().addMonths(1);
        
    Rent__c rent2 = new Rent__c();
        rent2.Contact__c = contactTest.Id;
        System.debug('contactTest.Id : '+contactTest.Id);

        rent2.Inventory_Item__c = inventoryItem.Id;
        System.debug('inventoryItem.Id : '+inventoryItem.Id);

        rent2.LocationDate__c = Date.today();
        rent2.CloseDate__c = Date.today().addMonths(1);
    
    Test.startTest();
    Database.SaveResult result = Database.insert(rent, false);
    Database.SaveResult result2 = Database.insert(rent2, false);
    Test.stopTest();

    Inventory_Item__c chckingStatus = [SELECT Status__c FROM Inventory_Item__c WHERE id = :inventoryItem.Id LIMIT 1];
    System.AssertEquals('Rented', chckingStatus.Status__c);

    System.Assert(result.isSuccess());
    System.Assert(!result2.isSuccess());

}
    @isTest
static void updateContactAndItemStatusTest() {
    Inventory__c inventory = new Inventory__c(RecordTypeId = '0128b000001MpG2AAK', Name = 'Test Movie');
    insert inventory;
    Inventory_Item__c inventoryItem = new Inventory_Item__c(Inventory__c = inventory.Id, Status__c = 'Available');
    insert inventoryItem;
    Inventory_Item__c inventoryItem2 = new Inventory_Item__c(Inventory__c = inventory.Id, Status__c = 'Available');
    insert inventoryItem2;
    Contact contactTest = new Contact(LastName = 'Test Movie');
    insert contactTest;
    RentBO re = new RentBO();

    Rent__c rent = new Rent__c();
    rent.Contact__c = contactTest.Id;
    rent.Inventory_Item__c = inventoryItem.Id;
    rent.LocationDate__c = Date.today();
    rent.CloseDate__c = Date.today().addMonths(1);

    insert rent;
    delete rent;

    Rent__c rent2 = new Rent__c();
    rent2.Contact__c = contactTest.Id;
    rent2.Inventory_Item__c = inventoryItem2.Id;
    rent2.LocationDate__c = Date.today();
    rent2.CloseDate__c = Date.today().addMonths(1);
    insert rent2;


    Rent__c rent3 = new Rent__c();
    rent3.Contact__c = contactTest.Id;
    rent3.Inventory_Item__c = inventoryItem.Id;
    rent3.LocationDate__c = Date.today();
    rent3.CloseDate__c = Date.today().addMonths(1);
    insert rent3;

    List<Rent__c> rentList = new List<Rent__c>();
    rentList.Add(rent);
    rentList.Add(rent2);
    rentList.Add(rent3);


    ReservedItem__c reserved1 = new ReservedItem__c();
    reserved1.Reservation__c = inventory.Id;
    reserved1.ContactName__c = contactTest.Id;
    reserved1.ReservationStatus__c = 'Waiting';

    ReservedItem__c reserved2 = new ReservedItem__c();
    reserved2.Reservation__c = inventory.Id;
    reserved2.ContactName__c = contactTest.Id;
    reserved2.ReservationStatus__c = 'Waiting';
    
    ReservedItem__c reserved3 = new ReservedItem__c();
    reserved3.Reservation__c = inventory.Id;
    reserved3.ContactName__c = contactTest.Id;
    reserved3.ReservationStatus__c = 'Waiting';
    
    insert reserved1;
    insert reserved2;
    insert reserved3;

    delete rentList;
    // Perform assertions on the expected changes caused by the trigger
    Contact checkingStatus = [SELECT ContactStatus__c FROM Contact WHERE Id = :contactTest.Id LIMIT 1];
    System.AssertEquals('Normal', checkingStatus.ContactStatus__c);
}
@isTest
static void setReservedItmCountingDownTest() {
    Inventory__c inventory = new Inventory__c(RecordTypeId = '0128b000001MpG2AAK', Name = 'Test Movie');
    insert inventory;
    Inventory_Item__c inventoryItem = new Inventory_Item__c(Inventory__c = inventory.Id, Status__c = 'Available');
    insert inventoryItem;
    Inventory_Item__c inventoryItem2 = new Inventory_Item__c(Inventory__c = inventory.Id, Status__c = 'Available');
    insert inventoryItem2;
    Inventory_Item__c inventoryItem3 = new Inventory_Item__c(Inventory__c = inventory.Id, Status__c = 'Available');
    insert inventoryItem3;
    Contact contactTest = new Contact(LastName = 'Test Movie');
    insert contactTest;
   
    Rent__c rent = new Rent__c();
    rent.Contact__c = contactTest.Id;
    rent.Inventory_Item__c = inventoryItem.Id;
    rent.LocationFinished__c = false;
    rent.LocationDate__c = Date.today();
    rent.CloseDate__c = Date.today().addMonths(1);
    insert rent;

    Rent__c rent2 = new Rent__c();
    rent2.Contact__c = contactTest.Id;
    rent2.Inventory_Item__c = inventoryItem2.Id;
    rent.LocationFinished__c = false;
    rent2.LocationDate__c = Date.today();
    rent2.CloseDate__c = Date.today().addMonths(1);
    insert rent2;


    Rent__c rent3 = new Rent__c();
    rent3.Contact__c = contactTest.Id;
    rent3.Inventory_Item__c = inventoryItem3.Id;
    rent.LocationFinished__c = false;
    rent3.LocationDate__c = Date.today();
    rent3.CloseDate__c = Date.today().addMonths(1);
    insert rent3;

    ReservedItem__c reserved1 = new ReservedItem__c();
    reserved1.Reservation__c = inventory.Id;
    reserved1.ContactName__c = contactTest.Id;
    reserved1.ReservationStatus__c = 'Waiting';

    ReservedItem__c reserved2 = new ReservedItem__c();
    reserved2.Reservation__c = inventory.Id;
    reserved2.ContactName__c = contactTest.Id;
    reserved2.ReservationStatus__c = 'Waiting';
    
    ReservedItem__c reserved3 = new ReservedItem__c();
    reserved3.Reservation__c = inventory.Id;
    reserved3.ContactName__c = contactTest.Id;
    reserved3.ReservationStatus__c = 'Waiting';
    
    insert reserved1;
    insert reserved2;
    insert reserved3;

    Map<Id, Rent__c> mapRent = new Map<Id, Rent__c>([SELECT Id, LocationFinished__c FROM Rent__c]);

    rent3.LocationFinished__c = true;
    rent2.LocationFinished__c = true;
    update rent3;
    update rent2;

    List<Rent__c> newList = new List<Rent__c>();
    newList.add(rent);
    newList.add(rent2);
    newList.add(rent3);

    RentBO re = new RentBO();

    Test.startTest();
    re.setReservedItmCountingDown(newList, mapRent);
    Test.stopTest();

    ReservedItem__c checkingStatus = [SELECT ReservationStatus__c FROM ReservedItem__c WHERE Id = :reserved1.Id LIMIT 1];
    System.AssertEquals('Time Counting Down', checkingStatus.ReservationStatus__c);
}
@isTest
static void blockStatusDefaltingTest() {
    Inventory__c inventory = new Inventory__c(RecordTypeId = '0128b000001MpG2AAK', Name = 'Test Movie');
    insert inventory;
    Inventory_Item__c inventoryItem = new Inventory_Item__c(Inventory__c = inventory.Id, Status__c = 'Available');
    insert inventoryItem;
    Inventory_Item__c inventoryItem2 = new Inventory_Item__c(Inventory__c = inventory.Id, Status__c = 'Available');
    insert inventoryItem2;
    Inventory_Item__c inventoryItem3 = new Inventory_Item__c(Inventory__c = inventory.Id, Status__c = 'Available');
    insert inventoryItem3;
    Contact contactTest = new Contact(LastName = 'Test Movie');
    contactTest.ContactStatus__c = 'Defaulting';
    insert contactTest;
   
    Rent__c rent = new Rent__c();
    rent.Contact__c = contactTest.Id;
    rent.Inventory_Item__c = inventoryItem.Id;

    
    Rent__c rent2 = new Rent__c();
    rent2.Contact__c = contactTest.Id;
    rent2.Inventory_Item__c = inventoryItem.Id;
    rent2.LocationFinished__c = false;
    rent2.LocationDate__c = Date.today().addMonths(1);
    rent2.CloseDate__c = Date.today();

    List<Rent__c> newList = new List<Rent__c>();
    newList.add(rent);

    List<Rent__c> newList2 = new List<Rent__c>();
    newList.add(rent2);

    RentBO re = new RentBO();

    Test.startTest();
    re.blockStatusDefalting(newList);
    re.blockStatusDefalting(newList2);
    Test.stopTest();

    // Perform assertions on the expected changes caused by the trigger
    Contact checkingStatus = [SELECT ContactStatus__c FROM Contact WHERE Id = :contactTest.Id LIMIT 1];
    System.AssertEquals('Defaulting', checkingStatus.ContactStatus__c);
}

}